### ISSUE TITLE
Addition of positional bias term

### ISSUE THREAD

**Issue by ilibarra** [theislab/mubind#103]
## Description
Here I am trying to brainstorm the positional bias term, which I think could be necessary to incorporate/test at this stage.
The positional bias term could be a filter p = Conv2D of (k, 4), where k is the length of the input sequence and 4 is the DNA dictionary. The term can also be batch-specific, meaning that we have to store it in the MultiBind instance and not in the BindingModes instance. This would be then a matrix of (b x p) e.g. For 8 batches the matrix is 8 x k x 4. A problem with the 3d tensor representation is that we have to mask k at some batches whenever there are differences in the length of the sequences.

Alternatively, the positional bias could also be a list of intercepts that are applied per position, sequence-independent.

1. @johschnee would you say the positional bias is (i) a list of Conv2D for positional biases of (k, 4), or (ii) a single vector of intercepts per position? Probably one is more complex than the other to implement, and we could setup both now.
2. Did you see any challenges when doing BindingModes as Cond2D or you would reconsider them being put as a 3d tensor and masking positions? 
http://pbdemo.x3dna.org/files/example_output/multiTF/index.html
![image](https://user-images.githubusercontent.com/2761796/209173539-c14e0bf7-87e4-4f7f-846e-f33fdde43f9a.png)

###Tasks

- [ ] incorporate positional_bias flag in MultiBind, and Conv2D (k, 4) referring to learnable positional biases as an additional term, with as many of those as batches. This is similar to the non-specific binding "intercept" we have atm.
- [ ] Include this term in the main forward function.
- [ ] activate grad during the intercept learning task and deactivate with intercept respectively during learning of other kernels.
